Финальное задание спринта 8. версия 1
zoomja/java-kanban pull request #1
Opened 2024-04-11 19:43 UTC by zoomja

2024-04-12 19:23 UTC, Fleaman777 requested changes

2024-04-12 19:23 UTC, Fleaman777 commented on src/Main.java
> +        manager1.getPrioritizedTasks().forEach(t -> System.out.println(t.getTittle()));
Вместо длинного написания Systenm.out.println можно использовать короткую версию через метод референс

2024-04-12 19:23 UTC, Fleaman777 commented on src/managers/InMemoryTaskManager.java
> +    private boolean checkOver(Task task) {
Приватные методы должны идти после публичных

2024-04-12 19:23 UTC, Fleaman777 commented on src/managers/InMemoryTaskManager.java
> +        if (checkOver(task)) {
А не должно ли быть подобной проверки для метода обновления ?

2024-04-12 19:23 UTC, Fleaman777 commented on src/managers/InMemoryTaskManager.java
> +        List<Subtask> listOfSub = getEpicById(epic.getId())
Как еще один вариант названия переменной: subtaskList

2024-04-12 19:23 UTC, Fleaman777 commented on src/managers/InMemoryTaskManager.java
> +                .max(LocalDateTime::compareTo).get();
Для оптимизации работы приложения, можно было бы попробовать всю логику прогнать в 1 стриме

2024-04-12 19:23 UTC, Fleaman777 commented on src/managers/InMemoryTaskManager.java
> +    private void calculateDateForEpic(Epic epic) {
Для оптимизации работы приложения, логику этого метода можно было бы попробовать сделать в 1 стриме

2024-04-12 19:23 UTC, Fleaman777 commented on src/test/TaskManagerTest.java
> +public class TaskManagerTest {
Неплохие тесты, но по заданию необходимо создать параметризированный абстрактный класс с тестами, от которого потом будут наследоваться другие 2 тестовых класса (для 2х менеджеров) 
При этом у FileBacked... должны быть еще несколько своих тестов

2024-04-12 19:23 UTC, Fleaman777 commented on src/test/Test.java
> +//
Необходимо еще дописать тесты на менеджер Истории, какие именно тесты написано в этой ТЗ. 

Так же проверь все ли написаны для менеджеров, эпиков и пр.

2024-04-13 19:55 UTC, zoomja commented on src/test/TaskManagerTest.java
> +public class TaskManagerTest {
Я не понял как это нужно сделать. можно пример или ссылку где можно об этом подробнее прочесть?

2024-04-23 12:54 UTC, Fleaman777 approved these changes

2024-04-23 16:41 UTC, merged